#
# Makefile
#
# Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/
#
# SPDX-License-Identifier:      GPL-2.0+
#

ifeq ($(CONFIG_SKIP_LOWLEVEL_INIT),)
obj-y   := mux.o
endif

obj-y := i10x.o pll.o gpmc_control.o fpga_led.o pmic.o cpu_rtc_ss.o
